workflows:
  ios-simulator:
    name: iOS Simulator (unsigned)
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS for simulator
        script: |
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app

  ios-device:
    name: iOS Device (signed .ipa AdHoc)
    environment:
      flutter: stable
    scripts:
      - name: Install deps
        script: flutter pub get
      - name: Build signed IPA (AdHoc)
        script: flutter build ipa --export-method ad-hoc
    artifacts:
      - build/ios/ipa/*.ipa

  ios-workflow:
    name: iOS Build & Deploy
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: eu.thefit.celia
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter dependencies
        script: flutter packages pub get
      - name: Generate code
        script: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update && cd ..
      - name: Flutter build iOS
        script: flutter build ios --release --no-codesign
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

